#ifndef USERSERVICECLIENT_GLOBAL_H
#define USERSERVICECLIENT_GLOBAL_H

#include <QtGlobal>

#ifndef USERSERVICECLIENT_EXPORT
#   ifdef USERSERVICECLIENT_LIBRARY
#       define USERSERVICECLIENT_EXPORT Q_DECL_EXPORT
#   else
#       define USERSERVICECLIENT_EXPORT Q_DECL_IMPORT
#   endif
#endif

#endif // USERSERVICECLIENT_GLOBAL_H
